FORMAT: 1A
HOST: http://api.tidepool.io

# Tidepool Messages
**Tidepool's api for exchanging short textual messages with timestamps.**

## Overview

The message-api stores and manipulates messages for Tidepool's applications


# Group Messages

## Health Check [/status]
### Retrieve status information [GET]
Returns a status health check with a list of status of its dependencies. 
If the server is operating properly and all dependencies are up and 
running, returns 200, otherwise 500. In either case, the body contains a 
list of up and down dependencies.


+ Response 200

        {
            "up" : [ "mongo" ],
            "down" : []
        }
    
+ Response 500

        If the server is *not* operating properly and one or more dependencies
        have failed to start or are no longer running.

        {
            "up" : [],
            "down" : [ "mongo" ]
        }

## Read a message [/read/{messageid}]
### Fetch the contents of a message [GET]
Returns the contents of a message by its ID number 
+ Parameters
    + messageid (required, string, `123abcd`) ... The ID of the message being requested.

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            

+ Response 200

        {
            message: {
                id: "ad8743",
                parentmessage: null,
                userid: "324a898",
                groupid: "678435",
                messagetext: "I can't believe I the whole thing",
                timestamp: "2013-12-25T12:34:56+0800"
            }
        }
        
+ Response 404

+ Response 400

## Get messages in a group in a range of time [/all/{groupid}{?starttime}{?endtime}]
### Retrieves all the messages in a given group for a range of time. [GET]
+ Parameters
    + groupid (required, string, `123abcd`) ... Tidepool-assigned user ID
    + starttime (required, string, `2013-11-25`) ... The first message to be returned will be later than or equal to this time.
    + endtime (optional, string, `2013-12-25`) ... The last date to be fetched with be earlier than or equal to this time.


+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
+ Response 200

        {
            messages: [
                {
                    id: "ad8743",
                    parentmessage: null,
                    userid: "324a898",
                    groupid: "678435",
                    messagetext: "Should I?",
                    timestamp: "2013-12-26T12:34:56+0800"
                },
                {
                    id: "a6f348",
                    parentmessage: "ad8743",
                    userid: "324a898",
                    groupid: "678435",
                    messagetext: "No.",
                    timestamp: "2013-12-26T13:04:22+0800"
                }
            ]
        }
        
+ Response 404


## Retrieve a thread [/thread/{messageid}]
### Get all the messages in a single thread [GET]
Get the messages in a thread starting at the messageid passed in. 200 if it succeeds, 404 if the message
ID was not valid.
+ Parameters
    + messageid (required, string, `123abcd`) ... The ID of the message being requested.

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
+ Response 200

        {
            messages: [
                {
                    id: "ad8743",
                    parentmessage: null,
                    userid: "324a898",
                    groupid: "678435",
                    messagetext: "Should I?",
                    timestamp: "2013-12-26T12:34:56+0800"
                },
                {
                    id: "a6f348",
                    parentmessage: "ad8743",
                    userid: "324a898",
                    groupid: "678435",
                    messagetext: "No.",
                    timestamp: "2013-12-26T13:04:22+0800"
                }
            ]
        }
        
        
+ Response 404

+ Response 400

## Send a message [/send/{groupid}]
### Send a message to a group [POST]
Sends a message to a given group (start a new thread). If found, returns
an object containing the id of the message created. 
+ Parameters
    + groupid (required, string, `123abcd`) ... Tidepool-assigned user ID

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
            
    + Body
    
            {
                parentmessage: '',
                userid: '12121212',
                groupid: '999',
                timestamp: '2013-11-28T23:07:40+00:00',
                messagetext: 'In three words I can sum up everything I have learned about life: it goes on.'
            }

+ Response 201

        {
            id: "12a34d5"
        }
        
## Reply to a message [/reply/{messageid}]
### Send a message to a group [POST]
Sends a message in response to a previous message. The parent of the message you send is the 
messageid that you reply to. If found, returns an object containing the id of the message 
created. The parentmessage parameter, if specified, is ignored.
+ Parameters
    + messageid (required, string, `123abcd`) ... The ID of the message being requested.

+ Request

    + Headers
    
            x-tidepool-session-token : 23sadf87.123840.aasd90JKj
            
            
    + Body
    
            {
                message: {
                    parentmessage: '',
                    userid: '12121212',
                    groupid: '999',
                    timestamp: '2013-11-28T23:07:40+00:00',
                    messagetext: 'In three words I can sum up everything I have learned about life: it goes on.'
                }
            }

+ Response 201

        {
            id: "12a34d5"
        }
        


